name: CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # seting docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # loging to hub
      - name: Log in to dockerhub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # build and push
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/fastapi-app:latest

      # run it 
      - name: Run the Docker container
        run: |
          docker run -d -p 8000:8000 ghcr.io/${{ github.repository_owner }}/fastapi-app:latest
